[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/about/*"
  to = "/#top"
  status = 301

[[redirects]]
  from = "/instructors/*"
  to = "/#resources"
  status = 301

[[redirects]]
  from = "/author/*"
  to = "/#team"
  status = 301
